# Generated by Django 2.0.13 on 2019-08-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propietario.Propietario')),
            ],
        ),
    ]
