# Generated by Django 2.0.13 on 2019-08-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
