# Generated by Django 2.0.13 on 2019-08-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
    ]
