# Generated by Django 2.0.13 on 2019-08-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=30)),
                ('apellido_propietario', models.CharField(max_length=30)),
                ('no_dpi', models.IntegerField()),
                ('no_licencia', models.IntegerField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
    ]
