# Generated by Django 2.0.13 on 2019-08-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='no_licencia',
        ),
        migrations.AlterField(
            model_name='propietario',
            name='no_dpi',
            field=models.CharField(max_length=20),
        ),
    ]
